// <auto-generated />
using System;
using AlbionKillnet.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbionKillnet.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619082452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AlbionKillnet.Core.Entities.KillEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("KillerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalVictimKillFame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VictimName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("KillEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
